apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: email-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-mail
  namespace: email-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-mail
  minReplicas: 2
  maxReplicas: 8
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-sub2
  namespace: email-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-sub2
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: email-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: email-platform
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-mail
  namespace: email-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: email-platform
      app.kubernetes.io/component: worker-mail
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-sub2
  namespace: email-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: email-platform
      app.kubernetes.io/component: worker-sub2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  namespace: email-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: email-platform
      app.kubernetes.io/component: web
