apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrate
  namespace: email-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: email-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-mail
  namespace: email-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sub2
  namespace: email-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: email-platform
automountServiceAccountToken: false
