upstream active_api {
    server api:8443;
    keepalive 32;
}
upstream active_web {
    server web:8443;
    keepalive 16;
}
map $host $active_api_tls_name {
    default api;
}
map $host $active_web_tls_name {
    default web;
}
